from django.urls import path
from .views import *


urlpatterns = [
    path('get-employee',  GetEmployee.as_view()),
    path('get-menu', GetMenu.as_view()),
    path('get-order', GetOrder.as_view()),
    path('get-hotel', GetHotel.as_view()),
    path('get-order-table', GetOrderTable.as_view()),
    path('get-order-food', GetFoodOrder.as_view()),
    path('get-restaurant', GetRestaurant.as_view()),
    path('get-workplace', GetWorkplace.as_view()),
    path('get-report', GetReport.as_view()),
    path('get-rating', GetRating.as_view()),
    path('get-address', GetAddress.as_view()),
    path('get-category', GetCategory.as_view()),
    path('get-git', GetGit.as_view()),
    path('get-sub-category-location', GetSubCategoryLocation.as_view()),
    path('fiter-hotel_by_name', hotel_by_name),
    path('fiter-hotel_by_call_centre', hotel_by_call_centre),
    path('fiter-restorant_by_name', restorant_by_name),
    path('fiter-restorant_by_call_centre', restorant_by_call_senter),
    path('fiter-employee_by_first_name', employee_by_first_name),
    path('fiter-employee_by_last_name', employee_by_last_name),
    path('fiter-employee_by_phone_number', employee_by_last_name),
    path('fiter-employee_by_age', employee_by_last_name),
    path('fiter-workplace_by_name', workplace_by_name),
    path('fiter-workplace_by_name', workplace_by_name),
    path('fiter-order_by_first_name', order_by_first_name),
    path('fiter-order_by_last_name', order_by_last_name),
    path('fiter-address_by_name', address_by_name),
    path('fiter-report_by_problem', report_by_problem),
    path('fiter-rating_by_work_place', rating_by_work_place),
    path('fiter-category_by_name', category_by_name),
    path('fiter-order_food_by_first_name', order_food_by_first_name),
    path('fiter-order_food_by_last_name', order_food_by_last_name),
    path('fiter-order_food_by_phone_number', order_food_by_phone_number),
    path('fiter-order_food_by_extra_phone_number', order_food_by_extra_phone_number),
    path('fiter-table_number_by_number', table_number_by_number),
    path('fiter-menu_by_name', menu_by_name),
    path('fiter-menu_by_price', menu_by_price),
    path('fiter-order_table_by_first_name', order_table_by_first_name),
    path('fiter-order_table_by_last_name', order_table_by_last_name),
    path('fiter-order_table_by_phone_number', order_table_by_phone_number),
    ]