from django.urls import path
from .views import *


urlpatterns = [
 path('create-employee', CreateEmployee.as_view()),
 path('update-employee/<int:pk>/', UpdateEmployee.as_view()),
 path('create-git/', CreateGit.as_view()),
 path('update-git/<int:pk>/', UpdateGit.as_view()),
 path('delete-git/<int:pk>/', DeleteGit.as_view()),
 path('create-hotel/', CreateHotel.as_view()),
 path('update-hotel/<int:pk>/', UpdateHotel.as_view()),
 path('delete-hotel/<int:pk>/', DeleteHotel.as_view()),
 path('create-restorant/', CreateRestorant.as_view()),
 path('update-restorant/<int:pk>/', UpdateRestorant.as_view()),
 path('delete-restorant/<int:pk>/', DeleteRestorant.as_view()),
 path('create-workplace/', CreateWorkplace.as_view()),
 path('update-workplace/<int:pk>/', UpdateWorkplace.as_view()),
 path('delete-workplace/<int:pk>/', DeleteWorkplace.as_view()),
 path('create-address/', CreateAddress.as_view()),
 path('update-address/<int:pk>/', UpdateAddress.as_view()),
 path('delete-address/<int:pk>/', DeleteAddress.as_view()),
 path('create-sub-category-location/', CreateSubCategoryLocation.as_view()),
 path('update-sub-category-location/<int:pk>/', UpdateSubCategoryLocation.as_view()),
 path('delete-sub-category-location/<int:pk>/', DeleteSubCategoryLocation.as_view()),
 path('create-order/', CreateOrder.as_view()),
 path('update-order/<int:pk>/', UpdateOrder.as_view()),
 path('delete-order/<int:pk>/', DeleteOrder.as_view()),
 path('create-rating/', CreateRating.as_view()),
 path('update-rating/<int:pk>/', UpdateRating.as_view()),
 path('delete-rating/<int:pk>/', DeleteRating.as_view()),
 path('create-category/', CreateCategory.as_view()),
 path('update-category/<int:pk>/', UpdateCategory.as_view()),
 path('delete-category/<int:pk>/', DeleteCategory.as_view()),
 path('create-menu/', CreateMenu.as_view()),
 path('update-menu/<int:pk>/', UpdateMenu.as_view()),
 path('delete-menu/<int:pk>/', DeleteMenu.as_view()),
 path('create-food-order/', CreateFoodOrder.as_view()),
 path('update-food-order/<int:pk>/', UpdateFoodOrder.as_view()),
 path('delete-food-order/<int:pk>/', DeleteFoodOrder.as_view()),
 path('create-table-order/', CreateOrderTable.as_view()),
 path('update-table-order/<int:pk>/', UpdateOrderTable.as_view()),
 path('delete-table-order/<int:pk>/', DeleteOrderTable.as_view()),

 ]